Small fixes and improvements
nim-lang/zip pull request #24
Opened 2017-08-12 15:50 UTC by arcvsduo

As discussed here: https://forum.nim-lang.org/t/3077

Added:
+ Replacing files in zip
+ Renaming/removing
+ Ability to switch between deflate/store method
+ Fixed path issues on Windows
+ static link by default

Note: not compatible with old libzip_all.c

2017-08-13 08:42 UTC, Araq commented
Does it work on Windows?

2017-08-14 08:49 UTC, arcvsduo commented
Yes, I'm on Win only. Though if someone is using MSVC instead of MinGW it would require other linking directives?

2017-08-17 19:19 UTC, dom96 requested changes

2017-08-17 19:19 UTC, dom96 commented on zip/libzip.nim
> +## Interface to the `libzip <http://www.nih.at/libzip/index.html>`_ library by
It seems fishy that GitHub thinks you've modified the whole file when the contents are the same...

I'm guessing you changed the newline characters for these files? You need to fix that.

2017-08-22 16:41 UTC, arcvsduo commented on zip/libzip.nim
> +## Interface to the `libzip <http://www.nih.at/libzip/index.html>`_ library by
Sure, done :)

2018-07-23 22:54 UTC, iffy commented
What's the status on this PR? I'm new to nim and think I want a statically linked libzip.  (I could be convinced otherwise, of course)

2018-07-24 05:36 UTC, Araq commented
This PR needs to keep the possibility to link against the DLL/lib.so file.

2019-03-03 23:31 UTC, brentp commented
it would be useful for me to have static linking to a more recent libzip. How having:
```
when defined(zipSharedLib):
  when defined(macosx):
    {.pragma: mydll, dynlib: "libzip(|2|4).dylib".}
  else:
    {.pragma: mydll, dynlib: "libzip(|2).so(|.4|.2|.1|.0)".}
else:
  {.passl: "-static".}
  {.passl: "-lzip".}
  {.passl: "-lz".}
```

as the change?

2019-03-04 11:44 UTC, Araq commented
@brentp Sounds good to me.

2019-03-04 15:37 UTC, brentp commented
@Anvell will you make those changes? Or shall I make a new PR from your branch?

2019-03-05 10:13 UTC, Anvell commented
Feel free to make new PR, I have not worked with Nim for some time :)

2025-07-15 22:29 UTC, closed without merging